// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWdevYb_PVFVZrAMgXRGstoXtVvUVQpFw',
    appId: '1:35957702446:web:2242417b0900f03b4744bf',
    messagingSenderId: '35957702446',
    projectId: 'chatapp-cad55',
    authDomain: 'chatapp-cad55.firebaseapp.com',
    storageBucket: 'chatapp-cad55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiBO1nZDNsNl3QB8IWXEJi8i5YLRREiZA',
    appId: '1:35957702446:android:4a532763f6030fe04744bf',
    messagingSenderId: '35957702446',
    projectId: 'chatapp-cad55',
    storageBucket: 'chatapp-cad55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NrAcVudbdemoN7LqPS37VeK44FI1ctk',
    appId: '1:35957702446:ios:c70617b0846e84f54744bf',
    messagingSenderId: '35957702446',
    projectId: 'chatapp-cad55',
    storageBucket: 'chatapp-cad55.appspot.com',
    iosClientId: '35957702446-5vo9cabu41igdd0pvkv1lc2rinqrc4vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2NrAcVudbdemoN7LqPS37VeK44FI1ctk',
    appId: '1:35957702446:ios:c70617b0846e84f54744bf',
    messagingSenderId: '35957702446',
    projectId: 'chatapp-cad55',
    storageBucket: 'chatapp-cad55.appspot.com',
    iosClientId: '35957702446-5vo9cabu41igdd0pvkv1lc2rinqrc4vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
